name: Lint

on:
    push:
        branches:
            - master
            - dev

jobs:
    lint:
        strategy:
            matrix:
                node-version: [ 12.x, 14.x ]
                platform: [ ubuntu-latest, macos-latest ]

        runs-on: ${{ matrix.platform }}

        steps:
            -   name: Install Node
                uses: actions/setup-node@v1
                with:
                    node-version: ${{ matrix.node-version }}

            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Install Packages
                run: npm install

            -   name: Test and generate coverage report
                run: npm run lint
